guild:
#   Enable or disable friendly fire
    friendly-fire: false
#   Enable or disable being able to see invisible guild members
    see-invisible: true

name:
# Minimum length of guild names
    min-length: 1
# Maximum length of guild names
    max-length: 64
# RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
    regex: "^[a-zA-Z0-9]*$"

prefix:
# Minimum length of the guild prefixes
    min-length: 1
# Maximum length of the guild prefixes
    max-length: 16
# RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
    regex: "^[a-zA-Z0-9]*$"
# Set the format for the prefix
    format: "&c[{prefix}] "

members:
# Set to -1 to disable
    max-members: 64

chat:
# Enable or disable custom chat formatting for players who are in a guild
    enable: true
# Custom chat format (only applied when the setting above is set to true)
#   - "{guild}" is replaced with the guild prefix
#   - "%s" (First) is replaced with the player's name
#   - "%s" (Second) is replaced with the player's message
    format: "{guild} <%s>: %s"

scoreboard:
# Enable or disable scoreboard below player's name which displays the guild he is in
    enable: true

database:
# Set the type of the database (Either JSON or MySQL)
    type: JSON
#  Uncomment when using MySQL
#    host: "127.0.0.1"
#    port: 3306
#    username: "root"
#    password: "password"
#    database: "guilds"
#    pool-size: 10

messages:
    command:
        error:
            console: "&cThis command can only be executed by a player!"
            args: "&cInvalid arguments! See /guilds help for more information"
            permission: "&cYou don't have permission to do that!"
            not-found: "&cCommand not found! See /guilds help for all commands"
            no-guild: "&cYou're not in a guild!"
            not-guildmaster: "&cYou're not the Guild Master of this guild"
            invalid_number: "&c{input} is not a valid number!"
            already-in-guild: "&cYou're already in a guild!"
            player-not-found: "&cPlayer '{player}' does not exist or is not online!"
            player-not-in-guild: "&cPlayer '{player}' is not in your guild!"
            invalid-role: "&cRole '{input}' does not exist!"
            guild-not-found: "&cGuild '{input}' cannot be found!"
        help:
            message: "&f/{command} {arguments} &7- &f{description}"
            next-page: "&7See /guilds help {next-page} for the next page"
        role:
            players: "{player} - {role}"
        create:
            successful: "&aGuild '{guild}' created successfully!"
            error: "&cSomething went wrong while creating your guild!"
            requirements: "&cYour guild's name does not match the requirements! You can only use alphanumeric characters and the length of the name cannot exceed 64"
            guild-name-taken: "&cThis name is already taken!"
        delete:
            successful: "&aDeleted guild successfully!"
            error: "&cSomething went wrong while deleting your guild!"
        info:
            header: "Information for {guild}"
            name: "Name: {guild} (Prefix: {prefix})"
            master: "Guild Master: {master}"
            member-count: "Current amount of members: {members}/64"
            rank: "Your rank: {rank}"
        promote:
            cannot-promote: "&cThis player cannot be promoted any further!"
        demote:
            cannot-demote: "&cThis player cannot be demoted any further!"
        chat:
            message: "&7&lGuild Chat> &r[{role}] {player}: {message}"
        accept:
            not-invited: "&cYou aren't invited for this guild!"
            guild-full: "&cThis guild is full!"
            successful: "&aYou joined guild '{guild}' successfully"
            player-joined: "&aPlayer '{player}' joined your guild!"
        invite:
            message: "&a{player} has invited you to the guild '{guild}"
            successful: "&aYou've successfully invited {player} to your guild!"
        leave:
            successful: "&aYou've successfully left your guild!"
            player-left: "&bPlayer '{player}' left your guild!"
        boot:
            successful: "Successfully kicked {player} from your guild!"
            kicked: "You have been kicked from your guild by {kicker}!"
            player-kicked: "Player '{player}' has been kicked from the guild by {kicker}!"