database:
# Set the type of the database (Either JSON or MySQL)
  type: JSON
#  Uncomment when using MySQL
#  credentials:
#    host: "127.0.0.1"
#    port: 3306
#    user: "root"
#    password: "password"
#    database: "guilds"

#Note: Current "messages" are temporary and only for testing, one day they will be made better
#TODO: Categorize these messages and make the messages better
messages:
  command-error-console: "&cThis command cannot be executed by the console!"
  command-error-args: "&cArguments specified are invalid!"
  command-error-permission: "&cYou do not have permission to execute this command!"
  command-error-not-found: "&cCommand not found!"
  command-error-no-guild: "&cYou're not in a guild!"
  command-error-not-guildmaster: "&cOnly the guild master can execute this command!"
  command-help-message: "{command} - {description}"
  command-help-error-number: "&cArgument entered is not a valid number"
  command-help-next-page: ""
  command-role-error-no-guild: ""
  command-role-error-role-not-found: ""
  command-role-players: ""
  command-create-error-in-guild: ""
  command-create-successful: "Guild created"
  command-create-error-create: "Error"
  command-delete-successful: ""
  command-delete-error: ""
  command-info-header: ""
  command-info-name: ""
  command-info-master: ""
  command-info-member-count: ""
  command-info-rank: ""