name:
# Minimum length of guild names
    min-length: 1
#   Maximum length of guild names
    max-length: 64
# RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
    regex: "^[a-zA-Z0-9]*$"

members:
# Set to -1 to disable
    max-members: 64

database:
# Set the type of the database (Either JSON or MySQL)
    type: JSON
#  Uncomment when using MySQL
#    host: "127.0.0.1"
#    port: 3306
#    username: "root"
#    password: "password"
#    database: "guilds"
#    pool-size: 10

#Note: Current "messages" are temporary and only for testing, one day they will be made better
#TODO: Categorize these messages and make the messages better
messages:
    command-error-console: "&cThis command can only be executed by a player"
    command-error-args: "&cInvalid arguments, see /guilds help for more information"
    command-error-permission: "&cYou do not have permission to execute this command"
    command-error-not-found: "&cInvalid command, see /guilds help for more information"
    command-error-no-guild: "&cGuild not found!"
    command-error-not-guildmaster: "&cYou're not the Guild Master"
    command-error-invalid-number: "Invalid number"
    command-error-already-in-guild: "You're already in a guild"
    command-error-player-not-found: "Player not found"
    command-help-message: "{command} - {description}"
    command-help-next-page: "do x to go to next page"
    command-role-error-role-not-found: "Invalid role"
    command-role-players: ""
    command-create-successful: "Created guild"
    command-create-error-create: "Error creating guild"
    command-delete-successful: "Guild removed"
    command-delete-error: "Error removing guild"
    command-info-header: ""
    command-info-name: ""
    command-info-master: ""
    command-info-member-count: ""
    command-info-rank: ""
    command-promote-cannot-promote: "Cannot promote"
    command-promote-player-not-in-guild: "Player not in guild"
    command-promote-invalid-role: "Invalid role"
    command-demote-player-not-in-guild: "Player not in guild"
    command-demote-cannot-demote: "Cannot demote"
    command-demote-invalid-role: "Invalid role"
    command-chat-message: ""
    command-accept-guild-not-found: "Guild not found"
    command-accept-not-invited: "Not invited"
    command-accept-successful: "Accepted"
    command-accept-player-joined: "Accepted"
    command-invite-message: "Accepted"
    command-invite-successful: "Accepted"
    command-leave-successful: "Left guild"
    command-leave-player-left: "Someone left the guild"
    command-boot-successful: "Success"
    command-boot-kicked: "You got kicked"
    command-boot-player-kicked: "Someone got kicked"