name: ${project.name}
version: ${project.version}
main: me.bramhaag.guilds.Main
author: bramhaag

commands:
  guild:
    aliases: "guilds"
    description: See the Guild commands

permissions:
  guilds.*:
    description: All permissions for the Guilds plugin
    children:
      guilds.command.accept: true
      guilds.command.boot: true
      guilds.command.chat: true
      guilds.command.create: true
      guilds.command.delete: true
      guilds.command.demote: true
      guilds.command.help: true
      guilds.command.info: true
      guilds.command.invite: true
      guilds.command.leave: true
      guilds.command.prefix: true
      guilds.command.promote: true
      guilds.command.role: true
    default: true